model_name: distilbert/distilbert-base-uncasee
dataset: dair-ai/emotion
num_labels: 6
batch_size: 16
epochs: 3
learning_rate: 2e-5
weight_decay: 0.01
output_dir: experiments/emotions-distilbert-lr2e-5